Update QA pytests
ACCESS-NRI/access-om2-configs pull request #58
Opened 2024-04-05 01:52 UTC by jo-basevi

- Add test for license file and contents, closes #56
- Change access-om2 nominal resolutions to strings, closes #57 
- Change metadata schema url to point to one schema commit -  as schemas should be backwards compatible

TODO:
Once https://github.com/ACCESS-NRI/schema/pull/19 (allow nominal resolutions to be a string) is merged, update `SCHEMA_VERSION` & `SCHEMA_COMMIT` in `test/test_config.py`

2024-04-05 05:26 UTC, aidanheerdegen commented
We also need to check there is no UUID set in the `metadata.yaml`.

I don't think it is harmful, but it is unnecessary and misleading, because this is a configuration, not an experiment, so it should not have a UUID.

2024-04-05 11:31 UTC, aidanheerdegen requested changes
Thanks for the quick turn-around on these ever-expanding list of tests.

2024-04-05 11:31 UTC, aidanheerdegen commented on test/test_config.py
> +LICENSE_URL = "https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt"
```suggestion
LICENSE_URL = "https://creativecommons.org/licenses/by/4.0/legalcode.txt"
```
Original URL is the sharealike license.

2024-04-05 11:31 UTC, aidanheerdegen commented on test/test_config.py
> +#TODO: Change to latest schema - 1-0-3? Otherwise use sets for nominal_resolution
Yes I think we should update to 1-0-3

https://raw.githubusercontent.com/ACCESS-NRI/schema/4b7207e47afe402a732c58741ff66acc5f93b8cf/au.org.access-nri/model/output/experiment-metadata/1-0-3.json

2024-04-05 11:31 UTC, aidanheerdegen commented on test/test_config.py
> +SCHEMA_COMMIT = "e9055da95093ec2faa555c090fc5af17923d1566"
```suggestion
SCHEMA_VERSION = "1-0-3"
SCHEMA_COMMIT = "4b7207e47afe402a732c58741ff66acc5f93b8cf"
```
I believe those are correct, but do feel free to check.

2024-04-07 23:34 UTC, jo-basevi commented
Thanks @aidanheerdegen  for those suggestions, and they all work.  I've added a check for UUID in metadata

2024-04-08 02:03 UTC, aidanheerdegen approved these changes
LGTM

2024-04-08 02:07 UTC, merged