Update 01deg jra55 iaf bgc
ACCESS-NRI/access-om2-configs pull request #68
Opened 2024-04-08 23:00 UTC by minghangli-uni

Update 01deg_jra55_iaf_bgc configuration. Related https://github.com/ACCESS-NRI/access-om2-configs/issues/48

2024-04-08 23:58 UTC, minghangli-uni commented
@aidanheerdegen It fails at QA test on

`AssertionError: Expect collate executable set to mppnccombine-fast`. 

But from the discussion in the #60, it appears that the decision was made not to add "-fast" for all configurations?

2024-04-09 02:44 UTC, aidanheerdegen commented
> But from the discussion in the #60, it appears that the decision was made not to add "-fast" for all configurations?

Definitely for all high res (0.25 and 0.1) models. Just the 1 degree it isn't necessary or even faster.

2024-04-09 10:33 UTC, aidanheerdegen requested changes
Sorry, just a couple more things to fix up.

2024-04-09 10:33 UTC, aidanheerdegen commented on config.yaml
> +      exe: /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/libaccessom2-git.2023.10.26=2023.10.26-ieiy3e7hidn4dzaqly3ly2yu45mecgq4/bin/yatm.exe
```suggestion
      exe: /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/libaccessom2-git.2023.10.26=2023.10.26-ltfg7jcn6t4cefotvj3kjnyu5nru26xo/bin/yatm.exebin/yatm.exe
```

2024-04-09 10:33 UTC, aidanheerdegen commented on config.yaml
> -  mpi: true
This should be `mpi: true` with `mppnccombine-fast`. Sorry for the confusion.

2024-04-09 12:33 UTC, aidanheerdegen commented
The test is failing because the `manifests/exe.yaml` has not been updated with the changed `yatm.exe`. You will need to comment out the 
```yaml
manifest:
  reproduce:
    exe: true
```
part of the `config.yaml` (or set to `false`) and do `payu setup` to update the manifests. Make sure `payu` doesn't add an `experiment_uuid` in this step. If it does this, and makes commit then `git revert` it and remove the `experiment_uuid`.

2024-04-10 05:31 UTC, aidanheerdegen approved these changes
Looks great. Thanks @minghangli-uni

2024-04-10 05:35 UTC, merged