Updates for 0.25 config
ACCESS-NRI/access-om2-configs pull request #85
Opened 2024-04-11 05:10 UTC by anton-seaice

Contributes to https://github.com/ACCESS-NRI/access-om2-configs/issues/17

Brings this config in line with the 1deg_jrado_ryf

2024-04-11 05:34 UTC, anton-seaice commented
I don't understand this failure:

`
AssertionError: Expect collate executable set to mppnccombine-fast
`

It's set to 
`  exe: /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-git.2023.11.09=2023.11.09-ewcdbrfukblyjxpkhd3mfkj4yxfolal4/bin/mppnccombine.spack
`

Which I believe is correct?

2024-04-11 06:08 UTC, aidanheerdegen commented
> Which I believe is correct?

https://github.com/ACCESS-NRI/access-om2-configs/pull/68#issuecomment-2044055563

2024-04-18 03:56 UTC, aidanheerdegen approved these changes
LGTM

2024-04-18 05:48 UTC, aidanheerdegen requested changes
Thanks. A few things to fix.

2024-04-18 05:48 UTC, aidanheerdegen commented on config.yaml
>        exe: /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/cice5-git.2023.10.19=2023.10.19-rh3xfkrgajya3ghtliacuhlx3pgvrzqs/bin/cice_auscom_1440x1080_48x40_480p.exe
```suggestion
      exe: /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/cice5-git.2023.10.19=2023.10.19-v3zncpqjj2gyseudbwiudolcjq3k3leo/bin/cice_auscom_1440x1080_48x40_480p.exe
```

Update to the latest ACCESS-OM2 release.

2024-04-18 05:48 UTC, aidanheerdegen commented on config.yaml
> +      exe: /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/libaccessom2-git.2023.10.26=2023.10.26-ltfg7jcn6t4cefotvj3kjnyu5nru26xo/bin/yatm.exe
This is correct but the mom exe needs to be updated too ([can't comment on unchanged code block](https://github.com/github/roadmap/issues/347), a real missing feature there GitHub)

```yaml
      exe: /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-git.2023.11.09=2023.11.09-qji4nlmr6utrribaiyhewe4je6mifguz/bin/fms_ACCESS-OM.x
```

2024-04-18 05:48 UTC, aidanheerdegen commented on metadata.yaml
> +  heat transfer.\nSpin up starts from a nominal year of 1 Jan 1900."
This is the 1 degree description.

2024-04-18 06:48 UTC, aidanheerdegen submitted a review, later dismissed
LGTM

2024-04-18 06:49 UTC, anton-seaice commented
> LGTM

Wrong answer ! :)

2024-04-18 23:38 UTC, aidanheerdegen approved these changes
Great, thanks for catching the catch I didn't.

2024-04-18 23:39 UTC, merged