Update 025deg jra55 iaf for access-nri build
ACCESS-NRI/access-om2-configs pull request #89
Opened 2024-04-15 01:04 UTC by anton-seaice

2024-04-16 01:21 UTC, anton-seaice commented on metadata.yaml
> +- repeat-year
```suggestion
- interannual
```

2024-04-18 05:53 UTC, aidanheerdegen requested changes
Missed a couple of the exe paths needing to be updated.

2024-04-18 05:53 UTC, aidanheerdegen commented on config.yaml
> +      exe: /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-git.2023.11.09=2023.11.09-ewcdbrfukblyjxpkhd3mfkj4yxfolal4/bin/fms_ACCESS-OM.x
```suggestion
      exe: /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-git.2023.11.09=2023.11.09-qji4nlmr6utrribaiyhewe4je6mifguz/bin/fms_ACCESS-OM.x
```
Missed this before.

2024-04-18 05:53 UTC, aidanheerdegen commented on config.yaml
> +      exe: /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/cice5-git.2023.10.19=2023.10.19-rh3xfkrgajya3ghtliacuhlx3pgvrzqs/bin/cice_auscom_1440x1080_48x40_480p.exe
```suggestion
      exe: /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/cice5-git.2023.10.19=2023.10.19-v3zncpqjj2gyseudbwiudolcjq3k3leo/bin/cice_auscom_1440x1080_48x40_480p.exe
```

2024-04-18 06:06 UTC, aidanheerdegen approved these changes
LGTM. Thanks.

2024-04-18 06:06 UTC, merged

2024-04-18 06:11 UTC, anton-seaice commented
We missed the manifests :). Shall i revert the merge or make a new PR or other ?